services:
  backend:
    container_name: backend
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - ./src/backend:/app
    ports:
      - "${LOCALHOST_PORT_BACKEND}:80"
      - "${LOCALHOST_PORT_DEBUGPY}:5678" # Expose debugpy port for remote debugging
    environment:
      - DEBUGPY_ENABLED=true # Enable debugpy
    
  db:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "${LOCALHOST_PORT_MONGO}:27017"
    volumes:
      - ./local/db/data/mongo:/data/db
    command: mongod --quiet --logpath /dev/null

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - "${LOCALHOST_PORT_AUTHSERVER}:8080"
    volumes:
      - ./local/auth/config-ssl.json:/app/config.json
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8080
      JSON_CONFIG_PATH: /app/config.json