name: Trigger auto deployment for {{_APP_CICD_CONTAINER_NAME}}

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ {{_APP_CICD_DEPLOYBRANCH}} ]

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.{{_APP_CICD_AZ_CREDS_SECRETNAME}} }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/{{_APP_CICD_APP_SOURCE_ROUTE}}
          dockerfilePath: Dockerfile
          registryUrl: {{_APP_CICD_REGISTRY_URL}}
          registryUsername: ${{ secrets.{{_APP_CICD_REGISTRY_USERNAME_SECRETNAME}} }}
          registryPassword: ${{ secrets.{{_APP_CICD_REGISTRY_PASSWORD_SECRETNAME}} }}
          containerAppName: {{_APP_CICD_CONTAINER_NAME}}
          resourceGroup: {{_APP_CICD_RESOURCE_GROUP_NAME}}
          imageToBuild: {{_APP_CICD_REGISTRY_URL}}/{{_APP_CICD_CONTAINER_NAME}}:${{ github.sha }}