name: Trigger auto deployment for backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ example-branch ]

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MAIN_AZ_CREDS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/example-container
          dockerfilePath: Dockerfile
          registryUrl: your-azure-container-registry.azurecr.io
          registryUsername: ${{ secrets.MAIN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAIN_REGISTRY_PASSWORD }}
          containerAppName: example-container
          resourceGroup: mrbeharapp-rg
          imageToBuild: your-azure-container-registry.azurecr.io/example-container:${{ github.sha }}